name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == matrix.event-name }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        GOARCH: [amd64, arm64]
        GOOS: [darwin, linux]
        exclude:
          - os: ubuntu-latest
            GOOS: darwin
          - os: macos-latest
            GOOS: linux            
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go test -v .
    - name: Build Client
      run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -o tcpbc-${{ matrix.GOOS }}-${{ matrix.GOARCH }} -v ./cmd/client
    - name: Build Server
      run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -o tcpbs-${GOOS}-${GOARCH} -v ./cmd/server
